### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@2.2.1

### ISSUE THREAD

**Issue by hankir** [souporserious/selectly#8]
npm install selectly --save
+-- selectly@0.4.0
`-- UNMET PEER DEPENDENCY webpack@2.2.1

javascript:
  import { Select, Option, utils } from 'selectly';
  ...

Select and utils is null

**Comment by jaybe78** [comment]
I got a different issue
node_modules/selectly/lib/Events-Handler.js:45
      document.addEventListener('mousedown', this._documentMouseDownHandler);

ReferenceError: document is not defined
    at EventsHandler.create (/home/jb/Documents/nui-risk-transition/nui-risk-messaging/node_modules/selectly/lib/Events-Handler.js:45:7)
    at new EventsHandler (/home/jb/Documents/nui-risk-transition/nui-risk-messaging/node_modules/selectly/lib/Events-Handler.js:39:10)
    at Object.<anonymous> (/home/jb/Documents/nui-risk-transition/nui-risk-messaging/node_modules/selectly/lib/Select.js:37:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by jaybe78** [comment]
The npm package installed looks different. It's not the same code as the the github

**Comment by basvdheijden** [comment]
@souporserious I've updated my webpack to 2.x. However it seems I cannot install this. Whatever I do, the "npm install" delivers a different package than the code inside this repo. Can you elaborate?

**Comment by agroth3** [comment]
I am experiencing the same issue. Any one have resolution?
